FORMAT: 1A
HOST: https://devrant.com/api

# devRant API
Welcome to the unofficial devRant API Documentation!
Here you will find documentation for all known endpoints

Documentation was written by [@Skayo](https://github.com/Skayo) and [@frogstair](https://github.com/frogstair)

# Group Rants

## Get Rant Feed [GET /devrant/rants/]

+ Parameters
    + app (required, number) - App Parameter
        + Default: `3`
    + sort (optional, string) - Sort rants by 'algo', 'top' or 'recent'
        + Default: `algo`
    + range (optional, string) - Time range of the rants to load. Either 'day', 'week', 'month' or 'all'
        + Default: `week`
    + limit (optional, number) - The maximum number of results to return. Used for pagination/infinite scroll
        + Default: `20`
    + skip: 0 (optional, number) - The amount of results to skip before returning. Used for pagination/infinite scroll
        + Default: `0`
    + token_id (optional, number) - Token ID of the user. Used for authentication
    + token_key (optional, string) - Token key of the user. Used for authentication
    + user_id (optional, number) - ID of the user on whose behalf the action is done. Used for authentication

+ Response 200 (application/json)
    ```js
    {
        "success": true,
        "rants": [
            {
                "id": 20123,
                "text": "Bla bla some long rant text with emojis and \n's",
                "score": 123,
                "created_time": 1518160633, // When the rant was created
                "attached_image": { // Empty string if there is no image
                    "url": "https://img.devrant.com/devrant/rant/imageName.jpg",
                    "width": 753,
                    "height": 546
                },
                "num_comments": 12,
                "tags": [
                    "some-tag"
                ],
                "vote_state": 0, // 1=upvoted, -1=downvoted, 0=unvoted, -2=no vote
                "edited": false,
                "rt": 1, // No clue what this is
                "rc": 1, // No clue what this is
                "user_id": 12301,
                "user_username": "User1",
                "user_score": 1234,
                "user_avatar": {
                    "b": "2a8b9d", // Avatar background color
                    "i": "v-18_c-3_b-4_g-m_9-1_1-2_16-3_3-3_8-3_7-3_5-4_12-2_6-7_10-9_2-48_15-11_18-4_4-4_19-3_20-14.jpg" // Avatar filename
                },
                "user_avatar_lg": {
                    "b": "2a8b9d", // Avatar background color
                    "i": "v-18_c-1_b-4_g-m_9-1_1-2_16-3_3-3_8-3_7-3_5-4_12-2_6-7_10-9_2-48_15-11_18-4_4-4_19-3_20-14.png" // Avatar filename
                },
                "user_dpp": 1 // 1 if user is devRant++, 0 if not devRant++
            },
            // ...
        ],
        "settings": { // Empty array when not authenticated
            "notif_state": "1", // 
            "notif_token": ""
        },
        "set": "5ee254ee76f3e", // Session hash
        "wrw": 212, // Weekly-Rant Week
        "dpp": 0, // 1 if devRant++, 0 if not devRant++, not set when not authenticated
        "num_notifs": 2, // Not set when not authenticated
        "unread": { // Not set when not authenticated
            "total": 2 // Same as "num_notifs"
        },
        "news": {
            "id": 321,
            "type": "intlink", // Internal Link (intlink) most of the time, not sure what other values are possible
            "headline": "Weekly Group Rant",
            "body": "Story of screenshare gone wrong?",
            "footer": "Add tag 'wk212' to your rant",
            "height": 100,
            "action": "grouprant" // What to do when clicked, "grouprant" means go to group rants section, not sure what other values are possible (I'm guessing there's "rant")
        }
    }
    ```