FORMAT: 1A
HOST: https://devrant.com/api

# devRant API
Welcome to the unofficial devRant API Documentation!
Here you will find documentation for all known endpoints

**Note:**<br>
All *POST* requests are done with header application/x-form-urlencoded, API blueprint does not support *POST* request documentation yet

***POST requests will not work in playground***

Documentation was written by [@Skayo](https://github.com/Skayo) and [@frogstair](https://github.com/frogstair)

Find an awesome-list [here](https://github.com/devRant-Community/awesome-devrant)


:[Rants](reference/rants.apib)
    
:[Authentication and user](reference/auth_and_user.apib)

:[Search](reference/search.apib)

:[Weeklys](reference/weeklys.apib)

:[User interaction](reference/user_interaction.apib)


# Data Structures

:[Rant](data-structures/Rant.apib)

:[RantFeed](data-structures/RantFeed.apib)

:[RantInFeed](data-structures/RantInFeed.apib)

:[Comment](data-structures/Comment.apib)

:[Profile](data-structures/Profile.apib)