# Authentication and user [/users/]

## Get access keys [POST /users/auth-token]

+ Parameters
    + app: 3 (required, number) - App ID parameter
    + username (required, string) - Username to login with
    + password (required, string) - Password to login with

+ Request (application/x-form-urlencoded)

+ Response 200 (application/json)
    + Attributes (object)
        + success: `true` (boolean)
        + auth_token (object)
            + id: 6712386 (number)
            + key: `tD5qeCHb6qvvfU4dLpFEWPL7YDNjA4hz7caGLW7M` (string)
            + expire_time: 6712386 (number)
            + user_id: 1085040 (number)

    + Body
        ```js
        {
            "success": true,
            "auth_token": {
                "id": 6712386,
                "key": "tD5qeCHb6qvvfU4dLpFEWPL7YDNjA4hz7caGLW7M",
                "expire_time": 6712386,
                "user_id": 1085040
            }
        }
        ```

+ Response 400 (application/json)
    + Attributes (object)
        + success: `true` (boolean)
        + error: `Invalid login credentials entered. Please try again.` (string)

    + Body
        ```js
        {
            "success": false,
            "error": "Invalid login credentials entered. Please try again."
        }
        ```

## Get user information [GET /users/{id}{?app,skip,content}]

+ Parameters
    + id (required, number) - User ID
    + app: 3 (required, number) - App ID parameter
    + skip: 0 (optional, number) - Amount of content to skip
    + content: `all` (optional, enum[string])
        Which type of content to load
        + Members
            + `all`
            + `rants`
            + `upvoted`
            + `comments`
            + `favorites`
            + `collabs`

+ Response 200 (application/json)
    ```js
    {
        "success": true,
        "profile": {
            "username": "User1",
            "score": 1234,
            "about": "Bla bla I'm a dev.",
            "location": "Idk",
            "created_time": 1514824661,      // Time the user joined devRant
            "skills": "No skills :/",
            "github": "User1",
            "website": "www.user1.com",
            "content": {
            "content": {
                "rants": [
                // Rants ...
                ],
                "upvoted": [
                // Upvoted Rants...
                ],
                "comments": [
                // Comments...
                ],
                "favorites": [
                // Favorited Rants...
                ]
            },
            "counts": {
                "rants": 12,
                "upvoted": 123,
                "comments": 12,
                "favorites": 1,
                "collabs": 2
            }
            },
            "avatar": {
            "b": "2a8b9d",
            "i": "v-18_c-1_b-4_g-m_9-1_1-1_16-7_3-1_8-1_7-1_5-1_12-1_6-16_10-6_2-27_11-3_18-2_4-1_19-1.png"
            },
            "avatar_sm": {
            "b": "2a8b9d",
            "i": "v-18_c-3_b-4_g-m_9-1_1-1_16-7_3-1_8-1_7-1_5-1_12-1_6-16_10-6_2-27_11-3_18-2_4-1_19-1.jpg"
            },
            "dpp": 0       // Bool indicator if the user is a devRant++ Member or not
        }
    }
    ```

## Get user ID [GET /get-user-id{?app,username}]

+ Parameters
    + app: 3 (required, number) - App ID parameter
    + username (required, string) - User username

+ Response 200 (application/json)
    ```js
    {
        "success": true,
        "user_id": 12301
    }
    ```

## Get list of supporters [GET /devrant/supporters{?app}]

+ Parameters
    + app: 3 (required, number) - App ID parameter

+ Response 200 (application/json)
    ```js
    {
        "items": [
            {
            "user": {
                "id": 12301,
                "name": "User1",
                "avatar": {
                "b": "2a8b9d",
                "i": "v-18_c-3_b-4_g-m_9-1_1-1_16-6_3-1_8-1_7-1_5-1_12-1_6-4_10-1_2-10_4-1.jpg"
                }
            },
            "start": 1496914102      // Time since the user is a member
            },
            {
            "user": {
                "id": 12302,
                "name": "User2",
                "avatar": {
                "b": "d55161",
                "i": "v-18_c-3_b-5_g-m_9-1_1-2_16-6_3-2_8-2_7-2_5-4_12-2_6-3_2-76_11-4_18-4_4-4_19-3_20-10_21-1.jpg"
                }
            },
            "start": 1496924123      // Time since the user is a member
            },
            // ...
        ]
    }
    ```