## Comment (object)
+ id: 2639015 (number)
+ rand_id: 10123 (number)
+ body: `This rant sucks!` (string)
+ score: -100 (number)
+ created_time: 1591901533 (number)
+ vote_state: 0 (number) - 1 = upvoted, -1 = downvoted, 0 = unvoted, -2 = no vote allowed
+ user_id: 5125 (number)
+ user_username: `User2` (string)
+ user_score: 10000 (number)
+ user_avatar (object)
    + b: `2a8b9d` (string) - Avatar background color
    + i: `v-37_c-3_b-6_g-m_9-1_1-6_16-4_3-13_8-1_7-1_5-1_12-6_17-2_6-2_10-5_2-26_22-2_15-10_11-3_18-2_19-1_4-1.jpg` (string) - Avatar filename