## Notif (object)
+ created_time: 1591546309 (number)
+ type: `content_vote` (string) - Type of ++ (form x_y where x is content/comment and y is vote/discuss)
+ read: 0 (number) - 0 = unread, 1 = read
+ rant_id: 2619313 (number)
+ uid: 2451362 (number) - ID of the user that "fired" the notif