## Profile (object)
+ username: `User1` (string)
+ score: 1234 (number)
+ about: `Bla bla I'm a dev.` (string)
+ location: `Idk` (string)
+ created_time: 1514824661 (number) - Time the user joined devRant
+ skills: `No skills :/` (string)
+ github: `User1` (string)
+ website: `www.user1.com` (string)
+ content (object)
    + rants (array[RantInFeed]) - User's rants
    + upvoted (array[RantInFeed]) - User's upvoted rants
    + comments (array[Comment]) - User's comments
    + favorites (array[RantInFeed]) - User's favorited rants
+ counts (object)
    + rants: 12 (number)
    + upvoted: 123 (number)
    + comments: 12 (number)
    + favorites: 1 (number)
    + collabs: 2 (number)
+ avatar (object)
	+ b: `2a8b9d` (string) - Avatar background color
	+ i: `v-18_c-1_b-4_g-m_9-1_1-1_16-7_3-1_8-1_7-1_5-1_12-1_6-16_10-6_2-27_11-3_18-2_4-1_19-1.png` (string) - Avatar file name
+ avatar_sm (object)
	+ b: `2a8b9d` (string) - Avatar background color
	+ i: `v-18_c-3_b-4_g-m_9-1_1-1_16-7_3-1_8-1_7-1_5-1_12-1_6-16_10-6_2-27_11-3_18-2_4-1_19-1.jpg` (string) - Avatar file name
+ dpp: 0 (number) - Numberic bool indicator if the user is a devRant++ member or not