## Rant (object)
+ id: 20123 (number)
+ text: `Bla bla some long rant text with emojis and \n's` (string)
+ score: 123 (number)
+ created_time: 1518160633 (number) - When the rant was created
+ attached_image (object) - Empty string if there is no image
    + url: `https://img.devrant.com/devrant/rant/imageName.jpg` (string)
    + width: 753 (number)
    + height: 546 (number)
+ num_comments: 12 (number)
+ tags (array[string])
+ vote_state: 0 (enum[number])
    + Members
        + 1 - Upvoted
        + -1 - Downvoted
        + 0 - Unvoted
        + -2 - No vote allowed
+ edited: false (boolean)
+ link: `rants/10123/some-strange-text-for-seo` (string) - Link to rant for social share etc. First part can be "rants" or "collabs"
+ rt: 1 (number) - No clue what this is
+ rc: 1 (number) - No clue what this is
+ links (array)
    + (object)
        + type: `url` (string) - Only urls are allowed in rants themselves so this should always be url
        + url: `https://github.com/User1/SomeRepo` (string)
        + short_url: `https://github.com/User...` (string) - Truncated url
        + title: `https://github.com/User...` (string)
        + start: 278 (number) - Starting position of the link
        + end: 313 (number) - Ending position of the link
        + special: 1 (number) - No clue what this is
+ special: 1 (number) - No clue what this is
+ c_type_long: `Existing open source project` (string) - Only if collab.
+ c_description: `Jungla is an alternative to GraphQL. Bla bla bla help pls` (string) - Only if collab.
+ c_tech_stack: `NodeJS` (string) - Only if collab.
+ c_team_size: `2` (string) - Only if collab.
+ c_url: `https://github.com/crazywolf132/Jungla` (string) - Only if collab.
+ user_id: 12301 (number)
+ user_username: `User1` (string)
+ user_score: 1234 (number)
+ user_avatar (object)
    + b: `2a8b9d` (string) - Avatar background color
    + i: `v-18_c-3_b-4_g-m_9-1_1-2_16-3_3-3_8-3_7-3_5-4_12-2_6-7_10-9_2-48_15-11_18-4_4-4_19-3_20-14.jpg` (string) - Avatar filename
+ user_avatar_lg (object)
    + b: `2a8b9d` (string) - Avatar background color
    + i: `v-18_c-1_b-4_g-m_9-1_1-2_16-3_3-3_8-3_7-3_5-4_12-2_6-7_10-9_2-48_15-11_18-4_4-4_19-3_20-14.png` (string) - Avatar filename
+ user_dpp: 1 (number) - 1 if user is devRant++, 0 if not devRant++