## RantInFeed (object)
+ id: 20123 (number)
+ text: `Bla bla some long rant text with emojis and \n's` (string)
+ score: 123 (number)
+ created_time: 1518160633 (number) - When the rant was created
+ attached_image (object) - Empty string if there is no image
    + url: `https://img.devrant.com/devrant/rant/imageName.jpg` (string)
    + width: 753 (number)
    + height: 546 (number)
+ num_comments: 12 (number)
+ tags (array[string])
+ vote_state: 0 (number) - 1 = upvoted, -1 = downvoted, 0 = unvoted, -2 = no vote allowed
+ edited: false (boolean)
+ rt: 1 (number) - No clue what this is
+ rc: 1 (number) - No clue what this is
+ user_id: 12301 (number)
+ user_username: `User1` (string)
+ user_score: 1234 (number)
+ user_avatar (object)
    + b: `2a8b9d` (string) - Avatar background color
    + i: `v-18_c-3_b-4_g-m_9-1_1-2_16-3_3-3_8-3_7-3_5-4_12-2_6-7_10-9_2-48_15-11_18-4_4-4_19-3_20-14.jpg` (string) - Avatar filename
+ user_avatar_lg (object)
    + b: `2a8b9d` (string) - Avatar background color
    + i: `v-18_c-1_b-4_g-m_9-1_1-2_16-3_3-3_8-3_7-3_5-4_12-2_6-7_10-9_2-48_15-11_18-4_4-4_19-3_20-14.png` (string) - Avatar filename
+ user_dpp: 1 (number) - 1 if user is devRant++, 0 if not devRant++