## Supporter (object)
+ user (object)
	+ id: 12301 (number)
	+ name: `User1`
	+ avatar (object)
		+ b: `2a8b9d` (string) - Avatar background color
		+ i: `v-18_c-1_b-4_g-m_9-1_1-1_16-7_3-1_8-1_7-1_5-1_12-1_6-16_10-6_2-27_11-3_18-2_4-1_19-1.png` (string) - Avatar file name
+ start: 1496914102 (number) - Timestamp when the user joined devRant++